### ISSUE TITLE
Trying to match to a typedef value in a receive statement causes "bad node type 44" error message

### ISSUE THREAD

**Issue by tgonzalez89** [nimble-code/Spin#17]
When I try to match a message in a receive statement I get a "bad node type 44" error message. This happens when the message's type is a typedef. The error message is rather cryptic and doesn't give much insight. I would like to know if this is a bug or the intended behavior. I don't think the documentation mentions anything related to the restriction of using struct types for doing matching in receive statements.

Code example:
```
typedef t {
    int i
}
init {
    chan c = [1] of {t}
    t x;
    !(c ?? [eval(x)]) // <--- ERROR
}
```

Link to StackOverflow question [here](https://stackoverflow.com/questions/59258481/trying-to-match-to-a-typedef-value-in-a-receive-statement-causes-bad-node-type).

**Comment by nimble-code** [comment]
that's a bug -- i'll check it out and find a fix if i can

**Comment by nimble-code** [comment]
fixed with update to pangen2.c and pangen4.c
not entirely sure that the fix covers all cases, but it does work for the example code and a few small variations of it

**Comment by tgonzalez89** [comment]
Thank you. The issue seems to be fixed.

**Comment by tgonzalez89** [comment]
I played around with the fixed code and with some cases where the struct type is more complex there seems to be more some issues. I attached two examples. In complex_id.pml I see the following error: "invalid end state". In test.pml I see this other error: "missing pars in receive". I think both files should pass the simulation.

[testcases.zip](https://github.com/nimble-code/Spin/files/3947945/testcases.zip)

**Comment by nimble-code** [comment]
made a further update -- 6 files changed -- that should now cover all cases.
i don't think the invalid endstate is in error, but let me know if that's not the case

**Comment by tgonzalez89** [comment]
Hmm... I still see the same issues. I simplified test.pml even further. The asserts here should pass but they are failing: pan:1: assertion violated Q_has(c, 1, receiver_id.t2.t1a.i, 1, sender_id1.t2.t1a.i, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
[test.txt](https://github.com/nimble-code/Spin/files/3952980/test.txt)

**Comment by nimble-code** [comment]
agreed -- good example -- that'll take some more checking

**Comment by nimble-code** [comment]
i have a fix -- will update once i've tested it a little more

**Comment by nimble-code** [comment]
fix uploaded -- 7 files changed -- this now passes the test.txt example and everything else I could think of.  fingers crossed....
